site_name: ArchLatam
site_url: https://archlatam.github.io/
site_description: Arch Linux LATAM Community
site_author: ArchLatam Team

repo_name: archlatam/archlatam.github.io
repo_url: https://github.com/archlatam/archlatam.github.io

copyright: Copyright &copy; 2024 ArchLatam

theme:
  name: material
  custom_dir: overrides
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share

extra_css:
  - stylesheets/colors.css
  - stylesheets/fonts.css
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4r8AmxSB2B
    - icon: fontawesome/brands/github
      link: https://github.com/archlatam

nav:
  - Home: index.md
  - Arch Linux Guide:
      - Archlinux-Guida/about-arch.md
  - Download:
      - Download/archlinux.md
      - Download/derivate.md
  - Other Guides:
      - Altre-Guide/comandi-linux.md
      - Altre-Guide/filesystem.md
      - Altre-Guide/pacman.md
      - Altre-Guide/aur.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.two_stage_index
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
