site_name: archlatam

nav:
  - "Home":
      - "Bienvenido": index.md
      - "Arch Linux":
          - "Que es Archlinux?": Archlinux-Guida/about-arch.md
          - "Descargar": Download/archlinux.md
          - "🇦🇷 Instalación de Arch Linux": "en/Archlinux-Guide/guida-es.md"
      - "Otras guías":
          - "Comandos Linux": "Altre-Guide/comando-linux.md"
          - "Pacman": "Altre-Guide/Pacman.md"
          - "AUR": "Altre-Guide/aur.md"
          - "Yay": "Altre-Guide/yay.md"
          - "Vim": "Altre-Guide/vim.md"
          - "Nano": "Altre-Guide/nano.md"
          - "Reflector": "Altre-Guide/reflector.md"

theme:
  name: material
  language: es
  logo: assets/archlatam.png

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - navigation.tabs
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - stylesheets/extra.css
  - stylesheets/fonts.css
  - stylesheets/colors.css

extra_javascript:
  - javascript/extra.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: " "
