site_name: ArchLatam
site_url: https://archlatam.github.io/
site_description: Arch Linux LATAM Community
site_author: ArchLatam Team

repo_name: archlatam/archlatam.github.io
repo_url: https://github.com/archlatam/archlatam.github.io

copyright: Copyright &copy; 2024 ArchLatam

font:
  text: Inter
  code: Fira Code

theme:
  name: material
  language: es

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share

  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  - media: "(prefers-color-scheme: light)"
    scheme: light
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

extra_css:
  - stylesheets/colors.css
  - stylesheets/fonts.css
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4r8AmxSB2B
    - icon: fontawesome/brands/github
      link: https://github.com/archlatam

nav:
  - Home: index.md

  - 'Arch Linux':
      - 'What is Arch Linux?': Archlinux-Guida/about-arch.md
      - 'Download': Download/archlinux.md
      - 'Derivatives': Download/Derivate.md
      - '- Installazione di Arch Linux': 'Archlinux-Guida/arch-guida.md'
      - '- Arch Linux Installation': 'en/Archlinux-Guide/guide.md'
      - '- Instalación de Arch Linux': 'en/Archlinux-Guide/guida-es.md'
      - '- Instalação do Arch Linux': 'en/Archlinux-Guide/guida-pt.md'
      - '- Installation d Arch Linux': 'en/Archlinux-Guide/guida-fr.md'
      - '- Arch Linux Installation': 'en/Archlinux-Guide/guida-de.md'
      - '- Arch Linuxのインストール': 'en/Archlinux-Guide/guida-jp.md'
      - '- 安装Arch Linux': 'en/Archlinux-Guide/guida-cn.md'
      - '- Arch Linux Installation': 'en/Archlinux-Guide/guida-in.md'
  - 'Other Guides':
      - 'Comandi Linux': 'Altre-Guide/comandi-linux.md'
      - 'File System': 'Altre-Guide/filesystem.md'
      - 'Pacman': 'Altre-Guide/Pacman.md'
      - 'AUR': 'Altre-Guide/aur.md'
      - 'Yay': 'Altre-Guide/yay.md'
      - 'Fstab': 'Altre-Guide/fstab.md'
      - 'Vim': 'Altre-Guide/vim.md'
      - 'Nano': 'Altre-Guide/nano.md'
      - 'Nvidia': 'Altre-Guide/nvidia.md'
      - 'AMD Manjaro mesa-codecs': 'Altre-Guide/amd.md'
      - 'Sudoers.d': 'Altre-Guide/sudoers.md'
      - 'Reflector': 'Altre-Guide/reflector.md'
      - 'Downgrade': 'Altre-Guide/downgrade.md'
      - 'Permessi': 'Altre-Guide/permessi.md'
      - 'Grub': 'Altre-Guide/grub.md'
      - 'Systemd-Boot': 'Altre-Guide/systemdboot.md'
      - 'Firewalld': 'Altre-Guide/firewald.md'
      - 'Rsync': 'Altre-Guide/rsync.md'
      - 'Timeshift': 'Altre-Guide/timeshift.md'
      - 'User Management': 'Altre-Guide/gestione-utenti.md'
      - 'NordVPN': 'Altre-Guide/nordvpn.md'

# markdown_extensions:
#   - attr_list
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.superfences
#   - codehilite
#   - toc:
#       permalink: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
